project:
  type: book

execute:
  eval: false

book:
  title: "学个毛生信"
  author: "Zhonghao Guo"
  date: "12/20/2025"
  cover-image: bookcover_v2.png
  cover-image-alt: "Book cover for 学个毛生信"
  favicon: favicon.svg
  sidebar:
    tools:
      - icon: bar-chart-line
        text: Analytics
        href: https://cloud.umami.is/share/eFyIpuQq1Nhdxj77
      - icon: github
        text: GitHub
        href: https://github.com/h4rvey-g/bioinfo-for-dummies
  chapters:
    - index.qmd
    - part: 1.AI.qmd
      chapters:
        - 1.1.AI-chat.qmd
        - 1.2.AI-code.qmd
        - 1.4.AI-service.qmd
    - part: 2.env_tool.qmd
      chapters:
        - 2.1.env-ide.qmd
        - 2.2.env-terminal.qmd
        - 2.3.env-mgmt.qmd
        - 2.4.env-version-ctrl.qmd
        - 2.5.env-pipelines.qmd
    - 3.bioinfo_exp.qmd
    - 4.acknowledge.qmd

bibliography: references.bib
date-modified: last-modified
date-format: "YYYY-MM-DD"

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, dark.scss]
    css: styles.scss
    include-in-header: include/umami.html
    include-after-body: include/cusdis.html
    page-footer:
      right: "最近更新：{{< meta date-modified >}}"
  pdf:
    documentclass: scrreprt
