project:
  type: book

execute:
  eval: false

book:
  title: "学个毛生信"
  author: "Harvey Guo"
  date: "10/30/2025"
  cover-image: bookcover_v2.png
  cover-image-alt: "Book cover for 学个毛生信"
  favicon: favicon.svg
  navbar:
    right:
      - icon: github
        aria-label: "Source on GitHub"
        href: https://github.com/h4rvey-g/bioinfo-for-dummies
  chapters:
    - index.qmd
    - part: 1.AI.qmd
      chapters:
        - 1.1.AI-chat.qmd
        - 1.2.AI-code.qmd
        - 1.4.AI-service.qmd
    - part: 2.env_tool.qmd
      chapters:
        - 2.1.env-ide.qmd
        - 2.2.env-terminal.qmd
        - 2.3.env-mgmt.qmd
        - 2.4.env-version-ctrl.qmd
        - 2.5.env-pipelines.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.scss
  pdf:
    documentclass: scrreprt
