#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Prefer tag info; fall back to short hash; mark dirty if needed.
version="$(git -C "$root" describe --tags --always --dirty 2>/dev/null || true)"
if [ -z "$version" ]; then
  version="unknown"
fi

# Use last commit date when possible; otherwise use current date.
commit_date="$(git -C "$root" log -1 --format=%cs 2>/dev/null || true)"
if [ -z "$commit_date" ]; then
  commit_date="$(date +%F)"
fi

cat > "$root/include/version.tex" <<EOF2
% Auto-generated by scripts/write_version.sh; do not edit by hand.
\\renewcommand{\\bookversion}{$version}
\\renewcommand{\\bookversiondate}{$commit_date}
EOF2
